export const QueryKeys = {
  CAT_SHOWS: ["catShows"],
  CAT_SHOW_BY_ID: (catShowId: number) => ["catShow", catShowId],
  USERS_CATS: ["usersCats"],
  USERS_CATS_BY_ID: (userId: string) => ["usersCats", userId],
  USERS: ["users"],
  USER: ["user"],
  USER_BY_ID: (userId: string) => ["user", userId],
  CATS: ["cats"],
  CAT: ["cat"],
  CAT_BY_ID: (catId: number) => ["cat", catId],
  CONFIRMATION_REQUESTS: ["confirmationRequests"],
  ROLES: ["roles"],
  CAT_BREEDS: ["catBreeds"],
};
